# Generated by Django 3.0.8 on 2020-07-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedq',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes'),
        ),
    ]
