# Generated by Django 3.0.8 on 2020-08-06 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200726_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedq',
            options={'ordering': ['slug']},
        ),
        migrations.AddField(
            model_name='generatedq',
            name='tweet_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='Time when Tweeted'),
        ),
    ]
