# Generated by Django 3.0.8 on 2020-08-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200806_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='About Text')),
                ('html', models.TextField(verbose_name='About Html')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
        ),
    ]
