# Generated by Django 3.0.8 on 2020-08-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedq',
            name='randomized',
            field=models.PositiveIntegerField(default=1, verbose_name='Random Order'),
        ),
    ]
