# Generated by Django 3.0.8 on 2020-08-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_generatedq_randomized'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Title'),
        ),
    ]
