# Generated by Django 3.0.8 on 2020-08-15 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200815_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedq',
            name='reddit_id',
            field=models.CharField(default='', max_length=30, verbose_name='Reddit Post Id'),
        ),
        migrations.AddField(
            model_name='generatedq',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='Time when Submitted'),
        ),
        migrations.AddField(
            model_name='generatedq',
            name='submitted',
            field=models.BooleanField(default=False, verbose_name='Submitted to Reddit'),
        ),
    ]
